### PR TITLE
Add View Collection

### PR DESCRIPTION
**Pull request by iniznet**
image

Taken & modified from: [Generate Model manually](https://github.com/mehrshaddarzi/wp-trait#generate-model-manually)
```php
public function admin_notices()
{
    $text = __('This Notice is a example from your plugin', $this->plugin->textdomain);

    // First Way
    $content = $this->view()
        ->attribute('text', $text)
        ->attribute([
            'description' => __('This is the description of your notice', $this->plugin->textdomain)
        ])
        ->render('notice');
    echo $this->add_alert($content, 'info');

    // Second Way
    $content = $this->view()->render('notice', [
        'text' => $text
    ], [
        'text' => __('Actually this is the real notice example from your plugin', $this->plugin->textdomain)
    ]);
    echo $this->add_alert($content, 'info');

    // Third Way
    $content = $this->view();
    $content->text = $text;
    echo $this->add_alert($content('notice'), 'info');

    // Property Way
    echo $this->add_alert($this->view->render('notice', [
	    'text' => $text . ' with property way'
    ]), 'info');
}
```

By default the template path: `plugin-directory/templates`
```html
<!-- plugin-directory/templates/notice.php -->
<strong style="display: block;"><?= $text; ?></strong>
<?php if (isset($description)): ?>
	<small><?= $description; ?></small>
<?php endif; ?>
```

### CODE REVIEW

**Comment by mehrshaddarzi** [comment]
Hi @iniznet 
Thanks a lot for this pull request.
We need View system in this Package.
I have a suggestion., please creating a feature for Overriding templates via a current active theme in WordPress,

```php
// First Check User Overriding Template in your Theme
if(!file_exists(get_template_directory().'/my-plugin-slug/alert/success.php'){

// If not Exist File, then Use Plugin templates
include $this->path.'/templates/alert/success.php';
}
```

Example in WooCommerce:
https://woocommerce.com/document/template-structure/#how-to-edit-files

**Comment by iniznet** [comment]
> Hi @iniznet Thanks a lot for this pull request. We need View system in this Package. I have a suggestion., please creating a feature for Overriding templates via a current active theme in WordPress,
> 
> ```
> // First Check User Overriding Template in your Theme
> if(!file_exists(get_template_directory().'/my-plugin-slug/alert/success.php'){
> 
> // If not Exist File, then Use Plugin templates
> include $this->path.'/templates/alert/success.php';
> }
> ```
> 
> Example in WooCommerce: https://woocommerce.com/document/template-structure/#how-to-edit-files

Done! What do you think?

```php
/** src/admin.php */
public function admin_notices()
{
	$text = __('This Notice is a example from your plugin', $this->plugin->textdomain);

	// First Way
	$content = $this->view()
		->attribute('text', $text)
		->attribute([
			'description' => __('This is the description of your notice', $this->plugin->textdomain)
		])
		->render('notice');
	echo $this->add_alert($content, 'info');

	// Second Way
	$content = $this->view()->render('notice', [
		'text' => $text
	], [
		'text' => __('Actually this is the real notice example from your plugin', $this->plugin->textdomain)
	]);
	echo $this->add_alert($content, 'info');

	// Third Way
	$content = $this->view();
	$content->text = $text;
	echo $this->add_alert($content('notice'), 'info');

	// Property Way
	echo $this->add_alert($this->view->render('notice', [
		'text' => $text . ' with property way'
	]), 'info');

	// Property Way with overriden view
	echo $this->add_alert($this->view->render('notice-override', [
		'text' => $text . ' with property way'
	]), 'info');
}
```

```html
<!-- themes/generatepress/plugin-slug/templates/notice-override.php -->
<strong style="display: block;"><?= $text . ' and overriden view'; ?></strong>
<?php if (isset($description)): ?>
	<small><?= $description; ?></small>
<?php endif; ?>
```

**Comment by iniznet** [comment]
I think I need some more tests before we merge this.

**Comment by iniznet** [comment]
I think so, it's necessary to have it so that the Developer is able to toggle their templates overriding.

**Comment by iniznet** [comment]
```php
/** src/admin.php:admin_notices() */

	// Property Way with overriden view
	echo $this->add_alert($this->view->render('notice-override-off', [
		'text' => $text . ' with property way and active theme should not override this view'
	], [], false), 'info');
```

```html
<!-- themes/generatepress/plugin-slug/templates/notice-override-off.php -->
<strong style="display: block;"><?= $text . ' but actually active theme can override this view'; ?></strong>
<?php if (isset($description)): ?>
	<small><?= $description; ?></small>
<?php endif; ?>
```

image

**Comment by mehrshaddarzi** [comment]
we doNot need `templates` in current theme dir.
please replace:

```php
$paths = [
                get_stylesheet_directory() . '/' . $this->plugin->slug . '/templates',
                get_template_directory() . '/' . $this->plugin->slug . '/templates',
            ];
```

To

```php
$paths = [
                get_stylesheet_directory() . '/' . $this->plugin->slug,
                get_template_directory() . '/' . $this->plugin->slug,
            ];
```

**Comment by iniznet** [comment]
That will break the overriding feature because I'm setting:
```php
protected function setPath($path = '', $plugin = null)
  {
      if (!$path && $plugin) {
          $path = $plugin->path . 'templates';
      }

      $this->path = $path;
  }
```

It will try to look: `themes/generatepress/plugin-slug/notice-override.php`

**Comment by iniznet** [comment]
My bad, after rechecking the woocommerce docs you're right.

**Comment by mehrshaddarzi** [comment]
I push this request in master branch.
Please Help me for writing document View Template in Readme.md.
Thanks

**Pull request merged**
